baseURL = 'https://lfsouth.com/'
languageCode = 'en-us'
title = 'lfsouth'
theme = 'yinyang'

[params]
headTitle = "lfsouth"
description = "Record my understandings"
mainSections = ["posts"]
favicon = "/logo.png"

[[params.socials]]
name = "Github"
link = "https://github.com/lfsouth"

[[params.socials]]
name = "About"
link = "https://lfsouth.com/about"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 2
