baseURL = 'https://lfsouth.com/'
languageCode = 'en-us'
title = 'lfsouth'
theme = 'yinyang'

[params]
headTitle = "lfsouth"
description = "share for myself and someone"
mainSections = ["posts"]
favicon = "/logo.png"

[[params.socials]]
name = "Github"
link = "https://github.com/lfsouth"

[[params.socials]]
name = "About"
link = "https://lfsouth.com/about"


